CANCEL = [["/cancel"]]
NEW_USER = [["Crear cuenta", "/cancel"]]
SELECT_ROLE = [["Estudiante", "Profesor"]]
TEACHER_LOGIN = [["Ingresar al aula", "Crear"]]
TEACHER_CREATE = [["Crear curso", "Crear aula"]]
TEACHER_MAIN_MENU = [["1", "2"]]
STUDENT_MAIN_MENU = [["1", "2"]]
